# Site settings
name: Thales Posella
description: "Professional Musician | Session Guitar Player"
url: "www.thalesposella.com"


# Delete the lines you don't need
# about 5 elements are recomended
github_username: platanus-xx
facebook_username: platanusmaple
twitter_username: thales_posella
youtube_username: thalesposella
instagram_username: thales_posella
email: contact@thalesposella.com


avatar: yes	
avatar_img_path: "imgs/logo.png"


front_img: yes
front_img_path: "imgs/Background.png"


favicon_img: yes
favicon_img_path: "imgs/favicon.png"
#favicon_img_path: "https://external.url/favicon.ico"


# Build settings
markdown: kramdown
permalink: pretty
