# Site settings
name: Tonantes Verdes Fritos
description: "Banda de Pop Rock especializada em shows dançantes para pubs, festas e casamentos."
release: ""
url: "www.tonantes.com"


# Delete the lines you don't need
# about 5 elements are recomended
github_username: platanus-xx
facebook_username: tonantes
twitter_username: tonantes
youtube_username: TonantesVerdesFritos
instagram_username: tonantes
email: naoetomates@tonantes.com


avatar: yes	
avatar_img_path: "imgs/logo.png"


front_img: yes
front_img_path: "imgs/Background.png"


favicon_img: yes
favicon_img_path: "imgs/favicon.png"
#favicon_img_path: "https://external.url/favicon.ico"


# Build settings
markdown: kramdown
permalink: pretty
