# Site settings
name: Tonantes Verdes Fritos
description: "Banda de Pop Rock especializada em shows dançantes para pubs, festas e casamentos."
release: "Os Tonantes verdes Fritos fazem um show que traz sorrisos para o rosto, refrãos para a garganta, passos de dança para os pés e um bom punhado de boas memórias à cabeça. É um show que convida a viajar um pouco no tempo sem estacionar no passado. Luís Bertocco (voz), Thales Posella (guitarra), Wellington Ruvieri (bateria) e Rafael Oliveira (baixo) tocam com personalidade e vigor um repertório de hits do pop e do rock que percorre o período que vem dos anos oitenta até os dias atuais e que tem seduzido platéias em todos os lugares por onde o quarteto passa.
A banda de Ribeirão Preto percorre os bares locais e um circuito de cidades do interior paulista como: Americana, Franca, São Carlos, Rio Preto, Batatais, Novo Horizonte e Limeira. Seja com uma versão enérgica de um pop radiofônico antigo, seja com aquela balada mais lenta com um riff de rock mais pesado que já te balançou ou com um hit mais contemporâneo do indie rock, os Tonantes farão um bom momento, talvez quase esquecido, voltar à lembrança, esperando sempre que ali seja vivido um novo belo instante a ser lembrado. Quando essa banda passar, vá ver."
url: "www.tonantes.com"


# Delete the lines you don't need
# about 5 elements are recomended
github_username: platanus-xx
facebook_username: tonantes
twitter_username: tonantes
youtube_username: TonantesVerdesFritos
instagram_username: tonantes
email: naoetomates@tonantes.com


avatar: yes	
avatar_img_path: "imgs/logo.png"

grid: yes	
grid_img_path: "imgs/grid/"

front_img: yes
front_img_path: "imgs/Background.png"


favicon_img: yes
favicon_img_path: "imgs/favicon.png"
#favicon_img_path: "https://external.url/favicon.ico"


# Build settings
markdown: kramdown
permalink: pretty
